# Generated by Django 5.1.7 on 2025-03-13 12:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_send_at', models.DateTimeField(default=datetime.datetime(2025, 3, 13, 22, 31, 50, 370347), verbose_name='Дата и время первой отправки')),
                ('end_send_at', models.DateTimeField(default=datetime.datetime(2025, 3, 14, 22, 31, 50, 370347), verbose_name='Дата и время окончания отправки')),
                ('status', models.CharField(choices=[('завершена', 'завершена'), ('создана', 'создана'), ('запущена', 'запущена')], default='создана', max_length=50)),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
                'ordering': ('first_send_at', 'status'),
                'permissions': [('can_cancel_mailing', 'Can cancel mailing')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Адрес должен быть уникальным', max_length=255, unique=True, verbose_name='Электронный адрес')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(verbose_name='Дата и время попытки отправки')),
                ('status', models.CharField(choices=[('SUCCESS', 'Успешно'), ('FAILURE', 'Не успешно')], max_length=10, verbose_name='статус')),
                ('mail_server_response', models.TextField(blank=True, null=True, verbose_name='Ответ сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailing.message'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(to='mailing.recipient', verbose_name='Получатели'),
        ),
    ]
