# Generated by Django 5.1.7 on 2025-03-17 12:58

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_options_alter_mailingattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['id'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'ordering': ['id'], 'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылки'},
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='mailingattempt',
            name='owner',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='end_send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 22, 58, 24, 116388), verbose_name='Дата и время окончания отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='first_send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 22, 58, 24, 116388), verbose_name='Дата и время первой отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing', to='mailing.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(related_name='mailing', to='mailing.recipient', verbose_name='Получатели'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('завершена', 'завершена'), ('создана', 'создана'), ('запущена', 'запущена')], default='CREATED', max_length=50, verbose_name='Статус'),
        ),
    ]
